#ifndef VSMC_INTERNAL_COMPILER_GCC_HPP
#define VSMC_INTERNAL_COMPILER_GCC_HPP

#if !__has_feature(cxx_explicit_conversions) || __cplusplus < 201103L
#undef VSMC_HAS_CXX11_EXPLICIT_CONVERSION
#else
#define VSMC_HAS_CXX11_EXPLICIT_CONVERSION
#endif

#endif // VSMC_INTERNAL_COMPILER_GCC_HPP
