#ifndef VSMC_INTERNAL_COMPILER_GCC_HPP
#define VSMC_INTERNAL_COMPILER_GCC_HPP

#if __GNUC__ < 4 || __GNUC__MINOR < 5 || __cplusplus < 201103L
#undef VSMC_HAS_CXX11_EXPLICIT_CONVERSION
#else
#define VSMC_HAS_CXX11_EXPLICIT_CONVERSION
#endif

#endif // VSMC_INTERNAL_COMPILER_GCC_HPP
