#ifndef VSMC_INTERNAL_COMPILER_INTEL_HPP
#define VSMC_INTERNAL_COMPILER_INTEL_HPP

#if __cplusplus >= 201103L

#if __INTEL_COMPILER >= 1100
#ifndef VSMC_HAS_CXX11_AUTO_TYPE
#define VSMC_HAS_CXX11_AUTO_TYPE 1
#endif
#else // __INTEL_COMPILER >= 1100
#ifndef VSMC_HAS_CXX11_AUTO_TYPE
#define VSMC_HAS_CXX11_AUTO_TYPE 0
#endif
#endif // __INTEL_COMPILER >= 1100

#if __INTEL_COMPILER >= 1300
#ifndef VSMC_HAS_CXX11_CONSTEXPR
#define VSMC_HAS_CXX11_CONSTEXPR 1
#endif
#else // __INTEL_COMPILER >= 1300
#ifndef VSMC_HAS_CXX11_CONSTEXPR
#define VSMC_HAS_CXX11_CONSTEXPR 0
#endif
#endif // __INTEL_COMPILER >= 1300

#if __INTEL_COMPILER >= 1100
#ifndef VSMC_HAS_CXX11_DECLTYPE
#define VSMC_HAS_CXX11_DECLTYPE 1
#endif
#else // __INTEL_COMPILER >= 1100
#ifndef VSMC_HAS_CXX11_DECLTYPE
#define VSMC_HAS_CXX11_DECLTYPE 0
#endif
#endif // __INTEL_COMPILER >= 1100

#if __INTEL_COMPILER >= 1300
#ifndef VSMC_HAS_CXX11_EXPLICIT_CONVERSIONS
#define VSMC_HAS_CXX11_EXPLICIT_CONVERSIONS 1
#endif
#else // __INTEL_COMPILER >= 1300
#ifndef VSMC_HAS_CXX11_EXPLICIT_CONVERSIONS
#define VSMC_HAS_CXX11_EXPLICIT_CONVERSIONS 0
#endif
#endif // __INTEL_COMPILER >= 1300

#endif // __cplusplus >= 201103L

#endif // VSMC_INTERNAL_COMPILER_INTEL_HPP
