#ifndef VSMC_INTERNAL_COMPILER_OPEN64_HPP
#define VSMC_INTERNAL_COMPILER_OPEN64_HPP

#ifndef VSMC_STATIC_INLINE
#define VSMC_STATIC_INLINE static inline
#endif

#ifndef VSMC_OPENMP_COMPILER_GOOD
#define VSMC_OPENMP_COMPILER_GOOD 1
#endif

#endif // VSMC_INTERNAL_COMPILER_OPEN64_HPP
