#ifndef VSMC_INTERNAL_COMPILER_SUNPRO_HPP
#define VSMC_INTERNAL_COMPILER_SUNPRO_HPP

#ifndef VSMC_STATIC_INLINE
#define VSMC_STATIC_INLINE static inline
#endif

#ifndef VSMC_OPENMP_COMPILER_GOOD
#define VSMC_OPENMP_COMPILER_GOOD 0
#endif

#endif // VSMC_INTERNAL_COMPILER_SUNPRO_HPP
