#ifndef V_SMC_UTILITIES_VERSION_HPP
#define V_SMC_UTILITIES_VERSION_HPP

#define V_SMC_VERSION_MAJOR 0
#define V_SMC_VERSION_MINOR 7
#define V_SMC_VERSION_PATCH 0

#endif // V_SMC_UTILITIES_VERSION_HPP
