#ifndef VSMC_UTILITY_OMP_WRAPPER_HPP
#define VSMC_UTILITY_OMP_WRAPPER_HPP

#include <vsmc/internal/config.hpp>
#include <omp.h>

#if !VSMC_OPENMP_COMPILER_GOOD
#error OPENMP SUPPORT WITH THIS COMPILER IS NOT TESTED IN VSMC
#endif

#endif // VSMC_UTILITY_OMP_WRAPPER_HPP
