FILE (READ ${PROJECT_SOURCE_DIR}/cmake/FindCXXMathLgamma.cpp
    CXX_MATH_LGAMMA_TEST_SOURCE)

IF (NOT DEFINED CXX_MATH_LGAMMA_FOUND)
    IF (NOT Boost_FOUND)
        INCLUDE (FindBoost)
    ENDIF (NOT Boost_FOUND)
    INCLUDE (CheckCXXSourceRuns)
    SET (SAFE_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})
    SET (CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES}
        ${Boost_INCLUDE_DIRS})
    CHECK_CXX_SOURCE_RUNS ("${CXX_MATH_LGAMMA_TEST_SOURCE}"
        CXX_MATH_LGAMMA_C99_FOUND)
    CHECK_CXX_SOURCE_RUNS ("${CXX_MATH_LGAMMA_TEST_SOURCE}"
        CXX_MATH_LGAMMA_STD_FOUND)
    IF (Boost_FOUND)
        CHECK_CXX_SOURCE_RUNS ("${CXX_MATH_LGAMMA_TEST_SOURCE}"
            CXX_MATH_LGAMMA_BOOST_FOUND)
    ENDIF (Boost_FOUND)
    IF (CXX_MATH_LGAMMA_C99_FOUND OR CXX_MATH_LGAMMA_STD_FOUND
            OR CXX_MATH_LGAMMA_BOOST_FOUND)
        SET (CXX_MATH_LGAMMA_FOUND TRUE CACHE BOOL "Found lgamma")
    ENDIF (CXX_MATH_LGAMMA_C99_FOUND OR CXX_MATH_LGAMMA_STD_FOUND
        OR CXX_MATH_LGAMMA_BOOST_FOUND)
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
ENDIF (NOT DEFINED CXX_MATH_LGAMMA_FOUND)
