IF (NOT Random123_INCLUDE_DIR)
    FIND_PATH (Random123_INCLUDE_DIR Random123/threefry.h
        PATHS ${Random123_INC_PATH} ENV CPATH)
ENDIF (NOT Random123_INCLUDE_DIR)

IF (Random123_INCLUDE_DIR)
    MESSAGE (STATUS "Found Random123 headers: ${Random123_INCLUDE_DIR}")
    SET (Random123_FOUND TRUE)
ELSE (Random123_INCLUDE_DIR)
    MESSAGE (STATUS "NOT Found Random123 headers")
    SET (Random123_FOUND FALSE)
ENDIF (Random123_INCLUDE_DIR)
