SET (Random123_FOUND TRUE)

FIND_PATH (Random123_INCLUDE_DIR Random123/threefry.h
    PATHS ${Random123_INC_PATH} ENV INCLUDE)
IF (${Random123_INCLUDE_DIR} STREQUAL Random123_INCLUDE_DIR-NOTFOUND)
    MESSAGE (STATUS "NOT Found Random123 headers")
    SET (Random123_FOUND FALSE)
ELSE (${Random123_INCLUDE_DIR} STREQUAL Random123_INCLUDE_DIR-NOTFOUND)
    MESSAGE (STATUS "Found Random123 headers: ${Random123_INCLUDE_DIR}")
ENDIF (${Random123_INCLUDE_DIR} STREQUAL Random123_INCLUDE_DIR-NOTFOUND)

IF (NOT Random123_FOUND)
    SET (Random123_INCLUDE_DIR)
ENDIF (NOT Random123_FOUND)
