SET (CXX_MATH_LGAMMA_TEST_SOURCE "
#include <cassert>
#include <cmath>

#ifdef CXX_MATH_LGAMMA_C99_FOUND
#define CXX_MATH_LGAMMA lgamma
#endif

#ifdef CXX_MATH_LGAMMA_STD_FOUND
#define CXX_MATH_LGAMMA std::lgamma
#endif

#ifdef CXX_MATH_LGAMMA_BOOST_FOUND
#include <boost/math/special_functions/gamma.hpp>
#define CXX_MATH_LGAMMA boost::math::lgamma
#endif

int main ()
{
    assert(std::abs(CXX_MATH_LGAMMA(2)) < 1e-10);

    return 0;
}
")

IF (NOT CXX_MATH_LGAMMA_FOUND)
    UNSET (CXX_MATH_LGAMMA_FOUND CACHE)
    UNSET (CXX_MATH_LGAMMA_C99_FOUND CACHE)
    UNSET (CXX_MATH_LGAMMA_STD_FOUND CACHE)
    UNSET (CXX_MATH_LGAMMA_BOOST_FOUND CACHE)
    INCLUDE (FindBoost)
    INCLUDE (CheckCXXSourceRuns)
    SET (SAFE_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})
    SET (CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES}
        ${Boost_INCLUDE_DIRS})
    CHECK_CXX_SOURCE_RUNS ("${CXX_MATH_LGAMMA_TEST_SOURCE}"
        CXX_MATH_LGAMMA_C99_FOUND)
    CHECK_CXX_SOURCE_RUNS ("${CXX_MATH_LGAMMA_TEST_SOURCE}"
        CXX_MATH_LGAMMA_STD_FOUND)
    IF (Boost_FOUND)
        CHECK_CXX_SOURCE_RUNS ("${CXX_MATH_LGAMMA_TEST_SOURCE}"
            CXX_MATH_LGAMMA_BOOST_FOUND)
    ENDIF (Boost_FOUND)
    IF (CXX_MATH_LGAMMA_C99_FOUND OR CXX_MATH_LGAMMA_STD_FOUND
            OR CXX_MATH_LGAMMA_BOOST_FOUND)
        SET (CXX_MATH_LGAMMA_FOUND TRUE CACHE BOOL "Found lgamma")
    ENDIF (CXX_MATH_LGAMMA_C99_FOUND OR CXX_MATH_LGAMMA_STD_FOUND
        OR CXX_MATH_LGAMMA_BOOST_FOUND)
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
ENDIF (NOT CXX_MATH_LGAMMA_FOUND)
