SET (OPENCL_FOUND TRUE)

IF (NOT OPENCL_LINK_LIBRARIES)
    FIND_LIBRARY (OPENCL_LINK_LIBRARIES OpenCL
        PATHS ${OPENCL_LIB_PATH} ENV LIBRARY_PATH)
ENDIF (NOT OPENCL_LINK_LIBRARIES)

IF (OPENCL_LINK_LIBRARIES)
    MESSAGE (STATUS "Found OpenCL libraries: ${OPENCL_LINK_LIBRARIES}")
ELSE (OPENCL_LINK_LIBRARIES)
    MESSAGE (STATUS "NOT Found OpenCL")
    SET (OPENCL_FOUND FALSE)
ENDIF (OPENCL_LINK_LIBRARIES)

IF (NOT OPENCL_INCLUDE_DIR)
    IF (APPLE)
        FIND_PATH (OPENCL_INCLUDE_DIR OpenCL/opencl.h
            PATHS ${OPENCL_INC_PATH} ENV CPATH)
    ELSE (APPLE)
        FIND_PATH (OPENCL_INCLUDE_DIR CL/opencl.h
            PATHS ${OPENCL_INC_PATH} ENV CPATH)
    ENDIF (APPLE)
ENDIF (NOT OPENCL_INCLUDE_DIR)

IF (OPENCL_INCLUDE_DIR)
    MESSAGE (STATUS "Found OpenCL headers: ${OPENCL_INCLUDE_DIR}")
ELSE (OPENCL_INCLUDE_DIR)
    MESSAGE (STATUS "NOT Found OpenCL headers")
    SET (OPENCL_FOUND FALSE)
ENDIF (OPENCL_INCLUDE_DIR)
