FILE (READ ${PROJECT_SOURCE_DIR}/cmake/vSMCFindRandom.cpp
    VSMC_RANDOM_TEST_SOURCE)

IF (NOT DEFINED VSMC_RANDOM_FOUND)
    INCLUDE (CheckCXXSourceRuns)
    INCLUDE (FindRandom123)
    SET (SAFE_CMAKE_REQUIRED_DEFINITIONS ${CMAKE_REQUIRED_DEFINITIONS})
    SET (SAFE_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})

    IF (RANDOM123_FOUND)
        SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES}
            ${Random123_INCLUDE_DIR})

        IF (VSMC_ENABLE_CXX11LIB_RANDOM)
            SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_REQUIRED_DEFINITIONS}
                -DVSMC_HAS_CXX11LIB_RANDOM=1 -DVSMC_USE_RANDOM123=1)
            CHECK_CXX_SOURCE_RUNS ("${VSMC_RANDOM_TEST_SOURCE}"
                VSMC_RANDOM123_STD_FOUND)
        ENDIF (VSMC_ENABLE_CXX11LIB_RANDOM)

        IF (NOT VSMC_RANDOM123_STD_FOUND)
            SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_REQUIRED_DEFINITIONS}
                -DVSMC_HAS_CXX11LIB_RANDOM=0 -DVSMC_USE_RANDOM123=1)
            CHECK_CXX_SOURCE_RUNS ("${VSMC_RANDOM_TEST_SOURCE}"
                VSMC_RANDOM123_BOOST_FOUND)
        ENDIF (NOT VSMC_RANDOM123_STD_FOUND)

        IF (VSMC_RANDOM123_STD_FOUND)
            SET (VSMC_RANDOM_STD_FOUND TRUE CACHE BOOL "Found C++11 random")
        ENDIF (VSMC_RANDOM123_STD_FOUND)

        IF (VSMC_RANDOM123_BOOST_FOUND)
            SET (VSMC_RANDOM_BOOST_FOUND TRUE CACHE BOOL  "Found Boost random")
        ENDIF (VSMC_RANDOM123_BOOST_FOUND)

        IF (VSMC_RANDOM123_STD_FOUND OR VSMC_RANDOM123_BOOST_FOUND)
            SET (VSMC_RANDOM123_FOUND TRUE CACHE BOOL "Found random123")
            SET (VSMC_RANDOM_FOUND TRUE CACHE BOOL "Found random")
        ELSE (VSMC_RANDOM123_STD_FOUND OR VSMC_RANDOM123_BOOST_FOUND)
            SET (VSMC_RANDOM123_FOUND FALSE CACHE BOOL "NOT Found random123")
        ENDIF (VSMC_RANDOM123_STD_FOUND OR VSMC_RANDOM123_BOOST_FOUND)
    ENDIF (RANDOM123_FOUND)

    IF (NOT VSMC_RANDOM_FOUND)
        SET (VSMC_RANDOM_STD_FOUND FALSE)
        SET (VSMC_RANDOM_BOOST_FOUND FALSE)

        IF (VSMC_ENABLE_CXX11LIB_RANDOM)
            SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_REQUIRED_DEFINITIONS}
                -DVSMC_HAS_CXX11LIB_RANDOM=1 -DVSMC_USE_RANDOM123=0)
            CHECK_CXX_SOURCE_RUNS ("${VSMC_RANDOM_TEST_SOURCE}"
                VSMC_RANDOM_STD_FOUND)
        ENDIF (VSMC_ENABLE_CXX11LIB_RANDOM)

        IF (NOT VSMC_RANDOM_STD_FOUND)
            SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_REQUIRED_DEFINITIONS}
                -DVSMC_HAS_CXX11LIB_RANDOM=0 -DVSMC_USE_RANDOM123=0)
            CHECK_CXX_SOURCE_RUNS ("${VSMC_RANDOM_TEST_SOURCE}"
                VSMC_RANDOM_BOOST_FOUND)
        ENDIF (NOT VSMC_RANDOM_STD_FOUND)

        IF (VSMC_RANDOM_STD_FOUND OR VSMC_RANDOM_BOOST_FOUND)
            SET (VSMC_RANDOM_FOUND TRUE CACHE BOOL "Found random")
        ENDIF (VSMC_RANDOM_STD_FOUND OR VSMC_RANDOM_BOOST_FOUND)
    ENDIF (NOT VSMC_RANDOM_FOUND)

    SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_REQUIRED_DEFINITIONS})
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
ENDIF (NOT DEFINED VSMC_RANDOM_FOUND)
