FILE (READ ${PROJECT_SOURCE_DIR}/test/utility/utility_stdtbb.cpp
    VSMC_STDTBB_TEST_SOURCE)

IF (NOT VSMC_THREAD_FOUND)
    UNSET (VSMC_STDTBB_FOUND CACHE)
    UNSET (VSMC_THREAD_FOUND CACHE)
ENDIF (NOT VSMC_THREAD_FOUND)

IF (NOT VSMC_FUTURE_FOUND)
    UNSET (VSMC_STDTBB_FOUND CACHE)
    UNSET (VSMC_FUTURE_FOUND CACHE)
ENDIF (NOT VSMC_FUTURE_FOUND)

IF (NOT VSMC_STDTBB_FOUND)
    INCLUDE (FindThreads)
    INCLUDE (CheckCXXSourceRuns)
    SET (SAFE_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRAREIS})
    SET (CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES}
        ${CMAKE_THREAD_LIBS_INIT})
    SET (SAFE_CMAKE_REQUIRED_DEFINITIONS ${CMAKE_REQUIRED_DEFINITIONS})
    SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_RQUIRED_DEFINITIONS}
        -DVSMC_HAS_CXX11LIB_FUTURE=1)
    CHECK_CXX_SOURCE_RUNS ("${VSMC_STDTBB_TEST_SOURCE}" VSMC_FUTURE_FOUND)
    SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_RQUIRED_DEFINITIONS}
        -DVSMC_HAS_CXX11LIB_FUTURE=0)
    CHECK_CXX_SOURCE_RUNS ("${VSMC_STDTBB_TEST_SOURCE}" VSMC_THREAD_FOUND)
    IF (VSMC_THREAD_FOUND OR VSMC_FUTURE_FOUND)
        SET (VSMC_THREAD_LINK_LIBRARIES ${CMAKE_THREAD_LIBS_INIT}
            CACHE STRING "Link to thread")
        SET (VSMC_STDTBB_FOUND TRUE CACHE BOOL "Found C++11 stdtbb")
    ENDIF (VSMC_THREAD_FOUND OR VSMC_FUTURE_FOUND)
    IF (VSMC_FUTURE_FOUND)
        SET (VSMC_FUTURE_FOUND TRUE CACHE BOOL "Found C++11 future")
    ENDIF (VSMC_FUTURE_FOUND)
    IF (VSMC_THREAD_FOUND)
        SET (VSMC_THREAD_FOUND TRUE CACHE BOOL "Found C++11 thread")
    ENDIF (VSMC_THREAD_FOUND)
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRAREIS})
    SET (CMAKE_REQUIRED_DEFINITIONS ${SAFE_CMAKE_RQUIRED_DEFINITIONS})
ENDIF (NOT VSMC_STDTBB_FOUND)
