FILE (READ ${PROJECT_SOURCE_DIR}/test/utility/src/utility_tuple_manip.cpp
    VSMC_TUPLE_TEST_SOURCE)

IF (NOT VSMC_TUPLE_FOUND)
    UNSET (VSMC_TUPLE_FOUND CACHE)
    INCLUDE (CheckCXXSourceRuns)
    CHECK_CXX_SOURCE_RUNS ("${VSMC_TUPLE_TEST_SOURCE}" VSMC_TUPLE_FOUND)
ENDIF (NOT VSMC_TUPLE_FOUND)
