FILE (READ ${PROJECT_SOURCE_DIR}/test/utility/utility_stdtbb.cpp
    VSMC_THREAD_TEST_SOURCE)

IF (NOT VSMC_THREAD_FOUND)
    UNSET (VSMC_THREAD_FOUND CACHE)
    INCLUDE (FindThreads)
    INCLUDE (CheckCXXSourceRuns)
    SET (SAFE_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRAREIS})
    SET (CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES}
        ${CMAKE_THREAD_LIBS_INIT})
    CHECK_CXX_SOURCE_RUNS ("${VSMC_THREAD_TEST_SOURCE}" VSMC_THREAD_FOUND)
    IF (VSMC_THREAD_FOUND)
        SET (VSMC_THREAD_LINK_LIBRARIES ${CMAKE_THREAD_LIBS_INIT}
            CACHE STRING "Link to thread")
        SET (VSMC_THREAD_FOUND TRUE CACHE BOOL "Found C++11 thread")
    ENDIF (VSMC_THREAD_FOUND)
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRAREIS})
ENDIF (NOT VSMC_THREAD_FOUND)
