FILE (READ ${PROJECT_SOURCE_DIR}/cmake/vSMCFindTuple.cpp
    VSMC_TUPLE_TEST_SOURCE)

IF (NOT DEFINED VSMC_TUPLE_FOUND AND VSMC_ENABLE_CXX11LIB_TUPE)
    INCLUDE (CheckCXXSourceRuns)
    CHECK_CXX_SOURCE_RUNS ("${VSMC_TUPLE_TEST_SOURCE}" VSMC_TUPLE_FOUND)
ENDIF (NOT DEFINED VSMC_TUPLE_FOUND AND VSMC_ENABLE_CXX11LIB_TUPE)
