FILE (READ ${PROJECT_SOURCE_DIR}/cmake/vSMCFindGCD.cpp VSMC_GCD_TEST_SOURCE)

INCLUDE (FindGCD)
IF (GCD_FOUND AND NOT DEFINED VSMC_GCD_FOUND)
    INCLUDE (CheckCXXSourceRuns)
    SET (SAFE_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})
    SET (SAFE_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES})
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES}
        ${GCD_INCLUDE_DIR})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES}
        ${GCD_LINK_LIBRARIES})
    CHECK_CXX_SOURCE_RUNS ("${VSMC_GCD_TEST_SOURCE}" VSMC_GCD_FOUND)
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES})
ENDIF (GCD_FOUND AND NOT DEFINED VSMC_GCD_FOUND)
