INCLUDE (FindGCD)
IF (GCD_FOUND AND NOT VSMC_GCD_FOUND)
    UNSET (VSMC_GCD_FOUND CACHE)
    INCLUDE (CheckCXXSourceRuns)
    FILE (READ ${PROJECT_SOURCE_DIR}/test/utility/utility_gcd.cpp
        GCD_TEST_SOURCE)
    SET (SAFE_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})
    SET (SAFE_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES})
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES}
        ${GCD_INCLUDE_DIR})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES}
        ${GCD_LINK_LIBRARIES})
    CHECK_CXX_SOURCE_RUNS ("${GCD_TEST_SOURCE}" VSMC_GCD_FOUND)
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES})
ENDIF (GCD_FOUND AND NOT VSMC_GCD_FOUND)
