SET (GTEST_TEST_SOURCE "
#include <gtest/gtest.h>
TEST(FOOTEST, foo) {ASSERT_EQ(1, 1);}
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}")

INCLUDE (FindGTest)
IF (GTEST_FOUND AND NOT DEFINED VSMC_GTEST_FOUND)
    INCLUDE (CheckCXXSourceRuns)
    SET (SAFE_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})
    SET (SAFE_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES})
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES}
        ${GTEST_INCLUDE_DIR})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES}
        ${GTEST_LINK_LIBRARIES})
    CHECK_CXX_SOURCE_RUNS ("${GTEST_TEST_SOURCE}" VSMC_GTEST_FOUND)
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES})
ENDIF (GTEST_FOUND AND NOT DEFINED VSMC_GTEST_FOUND)
