FILE (READ ${PROJECT_SOURCE_DIR}/cmake/vSMCFindChrono.cpp
    VSMC_CHRONO_TEST_SOURCE)

IF (NOT DEFINED VSMC_CHRONO_FOUND)
    INCLUDE (CheckCXXSourceRuns)
    CHECK_CXX_SOURCE_RUNS ("${VSMC_CHRONO_TEST_SOURCE}" VSMC_CHRONO_FOUND)
    IF (VSMC_CHRONO_FOUND)
        SET (VSMC_CHRONO_FOUND TRUE CACHE BOOL "Found C++11 chrono")
    ENDIF (VSMC_CHRONO_FOUND)
ENDIF (NOT DEFINED VSMC_CHRONO_FOUND)
