SET (VSMC_OPENCL_TEST_SOURCE "
#include <vsmc/utility/cl_query.hpp>

int main ()
{std::cout << vsmc::CLQuery() << std::endl;}
")
INCLUDE (FindOpenCL)
IF (OPENCL_FOUND AND NOT DEFINED VSMC_OPENCL_FOUND)
    INCLUDE (CheckCXXSourceRuns)
    SET (SAFE_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})
    SET (SAFE_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES})
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES}
        ${OpenCL_INCLUDE_DIR})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES}
        ${OpenCL_LINK_LIBRARIES})
    CHECK_CXX_SOURCE_RUNS ("${VSMC_OPENCL_TEST_SOURCE}" VSMC_OPENCL_FOUND)
    SET (CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
    SET (CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES})
ENDIF (OPENCL_FOUND AND NOT DEFINED VSMC_OPENCL_FOUND)
